#!/bin/bash

# /bin/wallpaper

if [ -z "$1" ]; then
  echo "Usage: $0 image_name"
  exit 1
fi

# Path to the wallpaper image
image_name="$1"

WALLPAPER_PATH="$HOME/Pictures/Wallpapers/${image_name}.png"

# Check if the file exists
if [[ ! -f "$WALLPAPER_PATH" ]]; then
    echo "File not found!"
    exit 1
fi

# Set the wallpaper
sudo cp $WALLPAPER_PATH /usr/share/wallpapers/Next/contents/images_dark/1920x1080.png
sudo cp $WALLPAPER_PATH /usr/share/wallpapers/Next/contents/images/1920x1080.png
sudo cp $WALLPAPER_PATH /usr/share/sddm/themes/breeze/preview.png
plasma-apply-wallpaperimage "$WALLPAPER_PATH"

echo "Wallpaper changed to $WALLPAPER_PATH"
wal -i $WALLPAPER_PATH
bash neofetch
